import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  root: {
    width: '100%',
    paddingLeft: 16,
    paddingRight: 16,
    marginTop: 25,
    marginBottom: 10,
  },
  filter: {
    backgroundColor: '#ffffff',
    width: '100%',
    borderRadius: 20,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
  },
  divider: {
    height: 10,
    width: 1,
    backgroundColor: '#8B8484',
  },
  input: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  search: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    direction: 'row',
    marginLeft: 10,
  },
  close: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    direction: 'row',
    marginRight: 10,
  },
  closeAll: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    direction: 'row',
    marginLeft: 10,
  },
  filters: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 10,
  },
  filtersCard: {
    backgroundColor: '#fff',
    padding: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 5,
    borderRadius: 20,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
});
